name: Deploy FE to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            set -e

            docker pull zmtechlabs/ivy-events-fe:latest

            docker stop ivy-events-fe || true
            docker rm ivy-events-fe || true

            docker run -d \
              --name ivy-events-fe \
              --network ivy-net \
              -p 80:80 \
              zmtechlabs/ivy-events-fe:latest

            echo "âœ… Frontend deployed"
